### PR TITLE
Bump to version 8.0.100

### PR DESCRIPTION
**Pull request by angeloc**
This series revamp a bit the meta-layer

* It bumps to version 8.0.100
* It refactor the bbclass in a way the user has more freedom while implementing the packages
* Fixes a bit of syntax

### CODE REVIEW

**Comment by angelo-zehnder** [comment]
@jeremy-prater The MR is ready, would you mind to give some feedback? Thanks!

**Comment by angeloc** [comment]
@jeremy-prater : I think the MR is ready. Would you mind to give some feedback?

**Comment by jeremy-prater** [comment]
Looks great! Thanks for the update to C# 8

**Comment by angeloc** [comment]
@jeremy-prater would you mind to sync master branch to kirkstone branch? It's pretty common to use the version branches instead of the main one.
Thanks!

**Pull request merged**
